### ISSUE TITLE
Issue with webUI-UX: the extension page is always in a loading state whenever it is launched

### ISSUE THREAD

**Issue by evakenshin** [ArtVentureX/sd-webui-agent-scheduler#64] opened 2023-07-05 05:42 UTC
Issue with webUI-UX: 
After installing the scheduler extension, the extension page is always in a loading state whenever it is launched. There are also some usage issues with certain functionalities. To resolve this, it requires clicking "reload UI" once to make it work properly. The problem doesn't occur after uninstalling the scheduler extension. How can this be resolved?
![image](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/13158959/cb7ef262-e6d0-4ca3-83f9-67fc88602d66)

**Comment by artventuredev** [comment] 2023-07-05 05:52
While I did make some basic changes to get the basic functionality up and running, I haven't had the chance to extensively test it or use `web-ui-ux` myself. So, bugs are definitely expected along the way.

Please describe your issue as much detail as possible, include the webui version/commit and all error messages from web ui console and browser console.

**Comment by evakenshin** [comment] 2023-07-05 12:16
fatal: unable to access 'https://github.com/anapnoe/stable-diffusion-webui-ux.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
venv "E:\Kenshin-SD-UX\WebUI-UX\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: ## 1.4.0
Commit hash: 355c0efed9f185d0f2259aa845e201ca44b53d49
Installing requirements

web ui console：

Launching Web UI with arguments: --medvram --theme dark --xformers --opt-channelslast --api --autolaunch
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: E:\Kenshin-SD-UX\WebUI-UX\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
dirname:  E:\Kenshin-SD-UX\WebUI-UX\localizations
localizations:  {'zh-Hans (Stable)': 'E:\\Kenshin-SD-UX\\WebUI-UX\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Stable).json', 'zh-Hans (Testing)': 'E:\\Kenshin-SD-UX\\WebUI-UX\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Testing).json'}
2023-07-05 20:10:25,930 - ControlNet - INFO - ControlNet v1.1.230
ControlNet preprocessor location: E:\Kenshin-SD-UX\WebUI-UX\extensions\sd-webui-controlnet\annotator\downloads
2023-07-05 20:10:26,108 - ControlNet - INFO - ControlNet v1.1.230
sd-webui-prompt-all-in-one background API service started successfully.
Loading weights [5493a0ec49] from E:\Kenshin-SD-UX\WebUI-UX\models\Stable-diffusion\AOM3A1B_orangemixs.safetensors
Creating model from config: E:\Kenshin-SD-UX\WebUI-UX\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: E:\Kenshin-SD-UX\WebUI-UX\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(4): bad-artist, bad-artist-anime, bad-hands-5, EasyNegative
Model loaded in 5.2s (load weights from disk: 0.6s, create model: 0.8s, apply weights to model: 0.7s, apply channels_last: 0.5s, apply half(): 0.8s, load VAE: 0.4s, calculate empty prompt: 1.3s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
[AgentScheduler] Runner is paused
[AgentScheduler] Registering APIs
Startup time: 24.2s (import torch: 2.6s, import gradio: 1.8s, import ldm: 0.8s, other imports: 1.4s, setup codeformer: 0.1s, list SD models: 0.2s, load scripts: 4.4s, create ui: 6.4s, gradio launch: 2.7s, add APIs: 0.1s, app_started_callback: 3.6s).
preload_extensions_git_metadata for 19 extensions took 13.36s

browser console.
Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at w (content.js:1:9328)
    at x (content.js:1:9047)
    at V (content.js:1:18901)
    at HTMLDocument.o (content.js:1:21159)
content.js:1 Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at w (content.js:1:9328)
    at x (content.js:1:9047)
    at V (content.js:1:18901)
    at HTMLDocument.i (content.js:1:21179)
:7860/openpose_editor_index:1     Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load source map: Could not load content for chrome-extension://cjmfiochlaffhnellbhffgnjocahinnh/dogEar/dogEar.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://cjmfiochlaffhnellbhffgnjocahinnh/storeVisits/storeVisits.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://cjmfiochlaffhnellbhffgnjocahinnh/dogEar/dogEar.css.map: System error: net::ERR_BLOCKED_BY_CLIENT
favicon.ico:1     GET http://127.0.0.1:7860/favicon.ico 403 (Forbidden)
civitai_helper.js?1686989830.0:337 gradio_ver:null
civitai_helper.js?1686989830.0:438 found active tab: lora
civitai_helper.js?1686989830.0:484 handle active extra tab
index.js?1687603903.3855338:1 sd-webui-3d-open-pose-editor: onUiLoaded
index.js:366 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '665')
    at Object.j [as submit] (index.js:366:20)
    at pe (Blocks.svelte:298:6)
    at je (Blocks.svelte:292:5)
j @ index.js:366
pe @ Blocks.svelte:298
je @ Blocks.svelte:292
await in je (async)
(anonymous) @ Blocks.svelte:364
bo @ Blocks.svelte:348
index.js:366 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '675')
    at Object.j [as submit] (index.js:366:20)
    at pe (Blocks.svelte:298:6)
    at je (Blocks.svelte:292:5)
j @ index.js:366
pe @ Blocks.svelte:298
je @ Blocks.svelte:292
await in je (async)
(anonymous) @ Blocks.svelte:364
bo @ Blocks.svelte:348
index.js:366 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '683')
    at Object.j [as submit] (index.js:366:20)
    at pe (Blocks.svelte:298:6)
    at je (Blocks.svelte:292:5)
j @ index.js:366
pe @ Blocks.svelte:298
je @ Blocks.svelte:292
await in je (async)
(anonymous) @ Blocks.svelte:364
bo @ Blocks.svelte:348
index.js:366 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '698')
    at Object.j [as submit] (index.js:366:20)
    at pe (Blocks.svelte:298:6)
    at je (Blocks.svelte:292:5)
j @ index.js:366
pe @ Blocks.svelte:298
je @ Blocks.svelte:292
await in je (async)
(anonymous) @ Blocks.svelte:364
bo @ Blocks.svelte:348
index.js:366 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '700')
    at Object.j [as submit] (index.js:366:20)
    at pe (Blocks.svelte:298:6)
    at je (Blocks.svelte:292:5)
j @ index.js:366
pe @ Blocks.svelte:298
je @ Blocks.svelte:292
await in je (async)
(anonymous) @ Blocks.svelte:364
bo @ Blocks.svelte:348
index.js:366 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '703')
    at Object.j [as submit] (index.js:366:20)
    at pe (Blocks.svelte:298:6)
    at je (Blocks.svelte:292:5)
j @ index.js:366
pe @ Blocks.svelte:298
je @ Blocks.svelte:292
await in je (async)
(anonymous) @ Blocks.svelte:364
bo @ Blocks.svelte:348
App.vue:424 config: {i18n: {…}, translate_apis: {…}, packages_state: Array(11), python: 'E:\\Kenshin-SD-UX\\WebUI-UX\\venv\\Scripts\\python.exe'}
index.js:366 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '75')
    at Object.j [as submit] (index.js:366:20)
    at pe (Blocks.svelte:298:6)
    at je (Blocks.svelte:292:5)
j @ index.js:366
pe @ Blocks.svelte:298
je @ Blocks.svelte:292
await in je (async)
(anonymous) @ Blocks.svelte:373
(anonymous) @ index.mjs:1170
Fr @ index.mjs:1170
f @ Button.svelte:12
(anonymous) @ index.mjs:1170
Fr @ index.mjs:1170
v @ Button.svelte:11
(anonymous) @ extraNetworks.js?1687000714.0:31
Show 4 more frames
index.js:366 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '304')
    at Object.j [as submit] (index.js:366:20)
    at pe (Blocks.svelte:298:6)
    at je (Blocks.svelte:292:5)
j @ index.js:366
pe @ Blocks.svelte:298
je @ Blocks.svelte:292
await in je (async)
(anonymous) @ Blocks.svelte:373
(anonymous) @ index.mjs:1170
Fr @ index.mjs:1170
f @ Button.svelte:12
(anonymous) @ index.mjs:1170
Fr @ index.mjs:1170
v @ Button.svelte:11
(anonymous) @ extraNetworks.js?1687000714.0:31
Show 4 more frames
index.js?a83964bb:85 i18next: languageChanged zh-TW
index.js?a83964bb:85 i18next: initialized {debug: true, initImmediate: true, ns: Array(1), defaultNS: 'common', fallbackLng: Array(1), …}
index.js?a83964bb:85 0.1.18  2023-04-15 21:20:24
index.js?a83964bb:102 @mediapipe/pose Module {Symbol(Symbol.toStringTag): 'Module'}
index.js?a83964bb:102 MyPose ƒ Pv(h){var w=this;h=h||{},this.h=new Ch({locateFile:h.locateFile,files:function(M){return[{url:"pose_solution_packed_assets_loader.js"},{simd:!1,url:"pose_solution_wasm_bin.js"},{simd:!0,url:"pose_sol…
index.js?a83964bb:3440 create editor
(anonymous) @ index.js?a83964bb:3440
zd @ index.js?a83964bb:40
Da @ index.js?a83964bb:40
(anonymous) @ index.js?a83964bb:40
T @ index.js?a83964bb:25
ee @ index.js?a83964bb:25
2index.js?a83964bb:3305 Infinity% loaded
index.js?a83964bb:3305 _o {isObject3D: true, uuid: 'db6bb05e-7859-401b-adfe-086cd92ccf2b', name: '', type: 'Group', parent: null, …}
index.js?a83964bb:3305 (2) [Wc, Wc]
index.js?a83964bb:3419 pushCommand
index.js?a83964bb:3419 method GetAppVersion []
index.js?a83964bb:3419 return {target: Window, origin: 'http://127.0.0.1:7860', data: {…}}data: {method: 'GetAppVersion', type: 'return', payload: '0.1.18'}origin: "http://127.0.0.1:7860"target: Window {0: Window, 1: Window, 2: Window, 3: Window, 4: Window, 5: Window, 6: Window, 7: Window, 8: Window, 9: Window, 10: Window, 11: Window, 12: Window, 13: Window, 14: Window, 15: Window, 16: Window, 17: Window, 18: Window, 19: Window, 20: Window, 21: Window, 22: Window, 23: Window, 24: Window, 25: Window, 26: Window, 27: Window, 28: Window, 29: Window, 30: Window, 31: Window, 32: Window, 33: Window, window: Window, self: Window, document: document, name: '', location: Location, …}[[Prototype]]: Object
index.js?1687603903.3855338:1 Method GetAppVersion MessageEvent {isTrusted: true, data: {…}, origin: 'http://127.0.0.1:7860', lastEventId: '', source: Window, …}
index.js?a83964bb:3419 method Pause []
index.js?a83964bb:3419 return {target: Window, origin: 'http://127.0.0.1:7860', data: {…}}data: {method: 'Pause', type: 'return', payload: undefined}origin: "http://127.0.0.1:7860"target: Window {0: Window, 1: Window, 2: Window, 3: Window, 4: Window, 5: Window, 6: Window, 7: Window, 8: Window, 9: Window, 10: Window, 11: Window, 12: Window, 13: Window, 14: Window, 15: Window, 16: Window, 17: Window, 18: Window, 19: Window, 20: Window, 21: Window, 22: Window, 23: Window, 24: Window, 25: Window, 26: Window, 27: Window, 28: Window, 29: Window, 30: Window, 31: Window, 32: Window, 33: Window, window: Window, self: Window, document: document, name: '', location: Location, …}[[Prototype]]: Object
index.js?1687603903.3855338:1 Method Pause MessageEvent {isTrusted: true, data: {…}, origin: 'http://127.0.0.1:7860', lastEventId: '', source: Window, …}isTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: Window {0: Window, 1: Window, 2: Window, 3: Window, 4: Window, 5: Window, 6: Window, 7: Window, 8: Window, 9: Window, 10: Window, 11: Window, 12: Window, 13: Window, 14: Window, 15: Window, 16: Window, 17: Window, 18: Window, 19: Window, 20: Window, 21: Window, 22: Window, 23: Window, 24: Window, 25: Window, 26: Window, 27: Window, 28: Window, 29: Window, 30: Window, 31: Window, 32: Window, 33: Window, window: Window, self: Window, document: document, name: '', location: Location, …}data: {cmd: 'openpose-3d', method: 'Pause', type: 'return', payload: undefined}defaultPrevented: falseeventPhase: 0lastEventId: ""origin: "http://127.0.0.1:7860"ports: []returnValue: truesource: Window {window: Window, self: Window, document: document, name: '', location: Location, …}srcElement: Window {0: Window, 1: Window, 2: Window, 3: Window, 4: Window, 5: Window, 6: Window, 7: Window, 8: Window, 9: Window, 10: Window, 11: Window, 12: Window, 13: Window, 14: Window, 15: Window, 16: Window, 17: Window, 18: Window, 19: Window, 20: Window, 21: Window, 22: Window, 23: Window, 24: Window, 25: Window, 26: Window, 27: Window, 28: Window, 29: Window, 30: Window, 31: Window, 32: Window, 33: Window, window: Window, self: Window, document: document, name: '', location: Location, …}target: Window {0: Window, 1: Window, 2: Window, 3: Window, 4: Window, 5: Window, 6: Window, 7: Window, 8: Window, 9: Window, 10: Window, 11: Window, 12: Window, 13: Window, 14: Window, 15: Window, 16: Window, 17: Window, 18: Window, 19: Window, 20: Window, 21: Window, 22: Window, 23: Window, 24: Window, 25: Window, 26: Window, 27: Window, 28: Window, 29: Window, 30: Window, 31: Window, 32: Window, 33: Window, window: Window, self: Window, document: document, name: '', location: Location, …}timeStamp: 28106.59999999404type: "message"userActivation: null[[Prototype]]: MessageEvent
index.js?a83964bb:3419 method Pause []length: 0[[Prototype]]: Array(0)
index.js?a83964bb:3419 return {target: Window, origin: 'http://127.0.0.1:7860', data: {…}}
index.js?1687603903.3855338:1 Method Pause MessageEvent {isTrusted: true, data: {…}, origin: 'http://127.0.0.1:7860', lastEventId: '', source: Window, …}
127.0.0.1/:1 Unchecked runtime.lastError: The message port closed before a response was received.
127.0.0.1/:1 Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by artventuredev** [comment] 2023-07-10 20:16
I couldn't replicate it on my end, even with the same commit for the `webui-ux`. The JavaScript errors you mentioned may be the cause, but they don't seem to be related to the extension. To dig deeper, I suggest disabling all of your extensions and then enabling them one by one to figure out what's causing the problem.

```
Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
at w (content.js:1:9328)
at x (content.js:1:9047)
at V (content.js:1:18901)
at HTMLDocument.o (content.js:1:21159)
content.js:1 Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
at w (content.js:1:9328)
at x (content.js:1:9047)
at V (content.js:1:18901)
at HTMLDocument.i (content.js:1:21179)
```

**Comment by evakenshin** [comment] 2023-07-18 10:03
maybe too late？
![image](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/13158959/031455a1-ae87-4d43-b2c4-48bd2c1f886f)

**Comment by evakenshin** [comment] 2023-07-18 10:12
But after reinstalling UX and then installing your extension, the problem disappeared. I don't know why.

**Comment by artventuredev** [comment] 2023-07-24 22:31
Great to hear that. I'll close the issue since it was resolved.

**Closed by artventuredev** 2023-07-24 22:31 UTC
