### ISSUE TITLE
sqlite intergrity error

### ISSUE THREAD

**Issue by hunny1389** [ArtVentureX/sd-webui-agent-scheduler#99] opened 2023-08-02 03:34 UTC
Hi all, I am getting this error

Exception adding task to database: (sqlite3.IntegrityError) UNIQUE constraint failed: task.id
[SQL: INSERT INTO task (id, api_task_id, api_task_callback, name, type, params, script_params, priority, status, result, bookmarked) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING created_at, updated_at]
[parameters: ('task(e5bq6ht8go3v90j)', None, None, None, 'txt2img', '{"args": {"id_task": "task(e5bq6ht8go3v90j)", "prompt": ",standing,   fashion, princess, ice valley, dynamic view, dynamic view" ... (742 characters truncated) ... st": {"username": null}, "sampler_name": "DPM++ 2M Karras"}, "checkpoint": "amIReal_V4.safetensors [1e0b0c6338]", "is_ui": true, "is_img2img": false}', <memory at 0x00000223A50D9600>, 1690927012180, 'pending', None, 0)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "C:\Pun\My AI experiments\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Pun\My AI experiments\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\sqlalchemy\engine\default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: task.id

The above exception was the direct cause of the following exception:

Any help on this ?

**Comment by artventuredev** [comment] 2023-08-02 14:17
@hunny1389  The issue is fixed on the latest commit, please give it a try.

**Closed** 2023-08-09 21:41 UTC
