### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class encountered in task_scheduler.py

### ISSUE THREAD

**Issue by designium** [ArtVentureX/sd-webui-agent-scheduler#55] opened 2023-06-30 01:06 UTC
## Description
I encountered a TypeError while running the task_scheduler module in the `sd-webui-agent-scheduler` extension of the `stable-diffusion-webui` system. The issue arises from the `issubclass()` function call in the `gradio` package. 

Here is the full error log:

        Error executing callback ui_tabs_callback for C:\Users\user_name\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py
        Traceback (most recent call last):
        File "C:\Users\user_name\stable-diffusion-webui\modules\script_callbacks.py", line 134, in ui_tabs_callback
        res += c.callback() or []
        File "C:\Users\user_name\stable-diffusion-webui\extensions\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 363, in on_ui_tab
        selected_task.change(
        File "C:\Users\user_name\stable-diffusion-webui\venv\lib\site-packages\gradio\events.py", line 132, in call
        dep, dep_index = self.trigger.set_event_trigger(
        File "C:\Users\user_name\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 217, in set_event_trigger
        check_function_inputs_match(fn, inputs, inputs_as_dict)
        File "C:\Users\user_name\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 869, in check_function_inputs_match
        if not is_special_typed_parameter(name):
        File "C:\Users\user_name\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 858, in is_special_typed_parameter
        is_event_data = issubclass(parameter_types.get(name, int), EventData)
        TypeError: issubclass() arg 1 must be a class

This error occurs when the first argument provided to `issubclass` is not a class type. In this case, the issue seems to be coming from the line of code in `gradio\utils.py` at line 858: `issubclass(parameter_types.get(name, int), EventData)`. Here, the `issubclass` function is checking if the type obtained from a dictionary `parameter_types` using the key `name` (or `int` as a default if the key doesn't exist) is a subclass of `EventData`.

## Possible Solutions

1. Confirm that all values in the `parameter_types` dictionary are class types.
2. Ensure that the `name` key used in `parameter_types.get(name, int)` exists in the `parameter_types` dictionary.
3. Verify that the `EventData` class is correctly defined and imported.

Looking forward to your advice or suggestions on how to resolve this issue. Thanks in advance for your help!

## Environment

- **OS:** Windows 11
- **Python Version:** 3.10.10
- **Agent scheduler: ** 8198489f (Thu Jun 29 03:24:05 2023)
python: 3.10.10  •  torch: 2.0.0+cu118  •  xformers: 0.0.17  •  gradio: 3.28.1  •  commit: 5ab7f213

**Comment by artventuredev** [comment] 2023-06-30 04:25
Please provide your SD webui version/commit hash for better debugging

**Comment by geoffrey-zsg** [comment] 2023-07-05 02:56
I think this error is caused by UI placement. I change UI placement, it work.
![WX20230705-105401@2x](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/54669908/a6d205a7-6f5c-492b-8d92-a90f33959a48)
![WX20230705-105540@2x](https://github.com/ArtVentureX/sd-webui-agent-scheduler/assets/54669908/a81b869e-d076-4383-a2c4-9b5071f906b0)

**Comment by artventuredev** [comment] 2023-07-15 20:19
@designium After investigating further, it seems that this problem stems from an outdated version of the gradio package. This issue has been resolved in the latest commit. I recommend updating the extension to the latest version and giving it another try.

**Closed** 2023-08-09 22:17 UTC
